test1 = [
    "Mr. Chan is a godsend, period. We have worked with many tutors over the years, and are so thankful to have finally found a tutor who 'gets it.'  Being a teacher with experience puts Mark in a different league from other tutors. His experience with students of all ages, in and out of the classroom, is a valuable asset as he has his finger on the pulse of what is truly needed to help our sons thrive.  Mark works with both our children on their different needs, with patience and grace. Mark has a knack for being able to connect with his students and 'meet them where they're at.' His lessons are engaging and challenging, as he works genuinely to help his students reach and see success within themselves. As a parent, I appreciate Mark being punctual and exceptionally reliable and for following up each session via text or email complete with description of what was worked on, so that I am kept in the loop of my child's progress and development. Since working with Mark, both of our children have improved their grades and have developed a stronger work ethic around school work in general. Our youngest son is now enjoying the confidence that comes from hard work and the 'never give up' attitude as he is realizing his potential.  For us, improved grades has led to improved sense of self for both our sons, and for that, we are eternally grateful to Mr. Chan.  S. van der Spuy, Oakville, ON"
]

test2 = [
    "Mark has been an exceptional tutor for our son through grades 9 and 10. Mark's dedication and expertise in math have been instrumental in our son's academic success. From the very beginning, Mark demonstrated an impressive ability to explain complex concepts in a way that was both understandable and engaging. His patient and encouraging approach helped our son build confidence and develop a genuine interest in Math. Mark's tutoring not only improved our son's grades but also instilled a deeper appreciation for math. We have seen remarkable progress in our son's performance and attitude towards learning, and we attribute much of this success to Mark's guidance and support. He is not only a skilled educator but also a mentor who genuinely cares about his students' growth. I wholeheartedly recommend Mark for tutoring. He has been an invaluable asset to our family, and I am confident he will continue to inspire and support many more students in their Academic journeys.  Anne H.  Oakville, ON"
]

test3 = [

]